# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0084_realmemoji_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='allow_edit_history',
            field=models.BooleanField(default=True),
        ),
    ]
